# Terminal life: foot, fish, starship, fastfetch, zoxide and the modern
# CLI replacements, plus baseline system CLI tools.
{
  flake.modules.nixos.terminal = { pkgs, ... }: {
    environment.systemPackages = with pkgs; [
      wget
      p7zip
      unzip
      step-cli
    ];
  };

  flake.modules.homeManager.terminal = { pkgs, ... }: {
    home.packages = with pkgs; [
      # Modern CLI Upgrades
      eza # Beautiful 'ls' replacement with icons
      bat # Beautiful 'cat' replacement with syntax highlighting
      btop # The coolest system monitor
    ];

    # Foot Terminal — colors live in the active theme file, switched at
    # runtime by theme-switch (see modules/theme/switcher.nix). Only NEW
    # foot windows pick up a theme change.
    programs.foot = {
      enable = true;
      settings = {
        main = {
          term = "xterm-256color";
          font = "JetBrainsMono Nerd Font:size=11";
          pad = "10x10";
          include = "~/.local/state/theme/foot.ini";
        };
        cursor = {
          style = "block";
          # (Cursor color removed here; Foot natively inverses colors for a perfect block)
        };
      };
    };

    # Starship Prompt — ~/.config/starship.toml is a per-theme file generated
    # by modules/theme/switcher.nix (prompt layout is defined there).
    programs.starship = {
      enable = true;
      enableFishIntegration = true;
    };

    # Fastfetch — ~/.config/fastfetch/config.jsonc is a per-theme file
    # generated by modules/theme/switcher.nix (gradient layout lives there).
    programs.fastfetch.enable = true;

    # Fish Shell
    programs.fish = {
      enable = true;
      interactiveShellInit = ''
        set -U fish_greeting ""
        fastfetch
      '';
      shellAliases = {
        ls = "eza --icons=always";
        ll = "eza -l --icons=always";
        la = "eza -la --icons=always";
        cat = "bat --style=plain";
        top = "btop";
      };
    };

    programs.zoxide = {
      enable = true;
      enableFishIntegration = true;
    };

    # Fuzzy finder: Ctrl+R history, Ctrl+T files, Alt+C cd
    programs.fzf = {
      enable = true;
      enableFishIntegration = true;
    };
  };
}
